id: A9BA10A0A
title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
  All Obstacles on the Path'
type: translation
pechas:
- I27A00200
- IAF019370
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:26.763580
  last_modified_at: 2023-01-04 11:33:26.763591
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I27A00200/10D6: 45A4
  IAF019370/71BE: 45A4
